### ISSUE TITLE
Game Crashes When Using Right-Click to Harvest Crops

### ISSUE THREAD

**Issue by Morningate** [BlakeBr0/PickleTweaks2#58]
**Describe the bug**
When using right-click to harvest crops, the game crashes.

**To Reproduce**
Harvest fully-grown wheat or other crops using the right-click method.

**Expected behavior**
Per mod description, it should simultaneously harvest the crops and plant new seeds.

**Screenshots / Scripts / Logs**
None available.

**Versions (please complete the following information):**
 - Minecraft: 1.16.2
 - Forge: forge-1.16.2-33.0.7
 - Cucumber: Cucumber-1.16.2-4.1.0
 - Pickle Tweaks: PickleTweaks-1.16.2-5.1.0

Thanks for your help. It's a great mod!

**Comment by BlakeBr0** [comment]
Can I get a crash log?

**Comment by Morningate** [comment]
Sure! Here you go. :)

---- Minecraft Crash Report ----
// Don't do that.

Time: 8/19/20 5:37 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(Lnet/minecraft/util/NonNullList;Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/BlockState;IFZLnet/minecraft/entity/player/PlayerEntity;)F
	at com.blakebr0.pickletweaks.feature.FeatureRightClickHarvest.onRightClickCrop(FeatureRightClickHarvest.java:58) ~[?:5.1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_26_FeatureRightClickHarvest_onRightClickCrop_RightClickBlock.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:772) ~[?:?] {re:classloading}
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:318) ~[?:?] {re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:889) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil$$Lambda$5856/845278455.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:729) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:156) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:712) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:706) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:692) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$5275/628513353.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 953967960 bytes (909 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 6.1.1+74+master.966c698
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.2-33.0.7.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.2-33.0.7.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.2-33.0.7.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.2-33.0.7.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.2-33.0.7.jar fml TRANSFORMATIONSERVICE 
	FML: 33.0
	Forge: net.minecraftforge:33.0.7
	FML Language Providers: 
		javafml@33.0
		minecraft@1
	Mod List: 
		forge-1.16.2-33.0.7-client.jar Minecraft {minecraft@1.16.2 DONE}
		forge-1.16.2-33.0.7-universal.jar Forge {forge@33.0.7 DONE}
		Cucumber-1.16.2-4.1.0.jar Cucumber Library {cucumber@4.1.0 DONE}
		PickleTweaks-1.16.2-5.1.0.jar Pickle Tweaks {pickletweaks@5.1.0 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['PECDad832'/130, l='ServerLevel[New World]', x=348.35, y=66.00, z=-115.31]]
	Data Packs: vanilla, mod:forge (incompatible), mod:cucumber, mod:pickletweaks
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
